### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by rgaufman** [Eierkopp/viddup#2]
Any instructions how to compile this on Mac?

**Comment by Eierkopp** [comment]
I haven't got a Mac, but there's not much to compile. The code itself is pure Python3. It requires ffmpeg to decode videos and numpy to compute the hashes. Both should be available on Macs as precompiled binary packages. The Python imageio package will autamatically download the right ffmpeg binary, if none is installed already.

For the knn library I'ld go for annoy. `pip3 install annoy` should be sufficient, given a C++ compiler/stdlib and the Python headers are available.
